package Main;

public enum CommandsEnum {
    ADD_INSTRUCTOR, LIST_INSTRUCTOR, ADD_TUTOR, LIST_TUTOR, ADD_STUDENT, LIST_STUDENT, ADD_ASIGNMENT, QUIT,
    LIST_SOLUTION, ADD_REVIEW, LIST_REVIEW, SEARCH_PLAGIARISM, ADD_PLAGIARISM, SUMMARY_TASKS, RESET, SUBMIT
}
