package Main;

public enum CommandsEnum {
    ADDINSTRUCTOR, LISTINSTRUCTOR, ADDTUTOR, LISTTUTOR, ADDSTUDENT, LISTSTUDENT, ADDASIGNMENT, QUIT,
    LISTSOLUTION, ADDREVIEW, LISTREVIEW, SEARCHPLAGIARISM, ADDPLAGIARISM, SUMMARYTASKS, RESET, SUBMIT
}
